version: '3.9'

services:
  webapp:
    build:
      context: .
      dockerfile: .\deploy\Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__npgsql=Host=localhost;Database=CarSalesDatabase;Username=postgres;Password=mypassword